CrazyEye-master/CrazyEye-master/CrazyEye/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from web import views,api_urls
from web import cus_admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
     #url(r'^myadmin/', include(cus_admin.admin_site.urls)),
    url(r'session_security/', include('session_security.urls')),
    url(r'^$',views.dashboard ),
    url(r'^hosts/$',views.hosts, name='host_list' ),
    url(r'^hosts/multi/$',views.hosts_multi),
    url(r'^hosts/crontab/$',views.crontab),
    url(r'^multi_task/log/deatail/(\d+)/$',views.multi_task_log_detail,name='multi_task_log_detail'),
    url(r'^hosts/multi/filetrans$',views.hosts_multi_filetrans),
    url(r'^host/detail/', views.host_detail),
    url(r'^api/',include(api_urls)),
    url(r'^personal/',views.personal,name='personal'),
    url(r'^user_audit/(\d+)/$',views.user_audit, name='user_audit'),
    url(r'^logout/',views.logout,name='logout'),

    url(r'^login/$',views.login,name='login'),
    url(r'^accounts/profile/$',views.personal),

]

CrazyEye-master/CrazyEye-master/web/models.py
#_*_coding:utf-8_*_
from django.db import models
import django
from django.contrib.auth.models import User
import datetime
# Create your models here.

class IDC(models.Model):
    name = models.CharField(max_length=64,unique=True)

    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = u'IDC'
        verbose_name_plural = u'IDC'

class Department(models.Model):
    name = models.CharField(max_length=64,unique=True)
    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = u'部门'
        verbose_name_plural = u'部门'

class Hosts(models.Model):
    hostname = models.CharField(max_length=64,unique=True)
    ip_addr = models.GenericIPAddressField(unique=True)
    system_type_choices = (
        ('windows','Windows'),
        ('linux', 'Linux/Unix')
    )
    idc = models.ForeignKey('IDC')
    system_type = models.CharField(choices=system_type_choices,max_length=32,default='linux')
    port = models.IntegerField(default=22)
    enabled = models.BooleanField(default=True,help_text=u'主机若不想被用户访问可以去掉此选项')
    #host_users = models.ForeignKey('HostUsers')
    #host_groups = models.ForeignKey('HostGroups')
    memo = models.CharField(max_length=128,blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __unicode__(self):
        return '%s(%s)' %(self.hostname,self.ip_addr)
    class Meta:
        verbose_name = u'主机'
        verbose_name_plural = u'主机'
class HostUsers(models.Model):
    auth_method_choices = (('ssh-password',"SSH/Password"),('ssh-key',"SSH/KEY"))
    auth_method = models.CharField(choices=auth_method_choices,max_length=16,help_text=u'如果选择SSH/KEY，请确保你的私钥文件已在settings.py中指定')
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=64,blank=True,null=True,help_text=u'如果auth_method选择的是SSH/KEY,那此处不需要填写..')
    memo = models.CharField(max_length=128,blank=True,null=True)
    def __unicode__(self):
        return '%s(%s)' %(self.username,self.password)
    class Meta:
        verbose_name = u'远程用户'
        verbose_name_plural = u'远程用户'
        unique_together = ('auth_method','password','username')
class BindHosts(models.Model):
    host = models.ForeignKey('Hosts')
    host_user = models.ForeignKey('HostUsers')
    host_group = models.ManyToManyField('HostGroups')
    enabled = models.BooleanField(default=True)
    def __unicode__(self):
        return '%s:%s' %(self.host.hostname,self.host_user.username)
    class Meta:
        unique_together = ("host", "host_user")
        verbose_name = u'主机与远程用户绑定'
        verbose_name_plural = u'主机远程与用户绑定'
    def get_groups(self):
            return ",\n".join([g.name for g in self.host_group.all()])

class HostGroups(models.Model):
    name = models.CharField(max_length=64,unique=True)
    memo = models.CharField(max_length=128,blank=True,null=True)
    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = u'主机组'
        verbose_name_plural = u'主机组'

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(unique=True,max_length=32)
    department = models.ForeignKey('Department',verbose_name=u'部门')
    #user_groups = models.ManyToManyField('PUserGroups') #might use it in the future version
    host_groups = models.ManyToManyField('HostGroups',verbose_name=u'授权主机组',blank=True)
    bind_hosts = models.ManyToManyField('BindHosts',verbose_name=u'授权主机',blank=True)
    valid_begin_time = models.DateTimeField(default=django.utils.timezone.now)
    valid_end_time = models.DateTimeField()

    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = u'CrazyEye账户'
        verbose_name_plural = u'CrazyEye账户'

class SessionTrack(models.Model):

    date = models.DateTimeField(default=django.utils.timezone.now)
    closed = models.BooleanField(default=False)
    def __unicode__(self):
        return '%s' %self.id

class AuditLog(models.Model):
    session = models.ForeignKey(SessionTrack)
    user = models.ForeignKey('UserProfile')
    host = models.ForeignKey('BindHosts')
    action_choices = (
        (0,'CMD'),
        (1,'Login'),
        (2,'Logout'),
        (3,'GetFile'),
        (4,'SendFile'),
        (5,'exception'),
    )
    action_type = models.IntegerField(choices=action_choices,default=0)
    cmd = models.TextField()
    memo = models.CharField(max_length=128,blank=True,null=True)
    date = models.DateTimeField()


    def __unicode__(self):
        return '%s-->%s@%s:%s' %(self.user.user.username,self.host.host_user.username,self.host.host.ip_addr,self.cmd)
    class Meta:
        verbose_name = u'审计日志'
        verbose_name_plural = u'审计日志'



class TaskLog(models.Model):
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(null=True,blank=True)
    task_type_choices = (('cmd',"CMD"),('file_send',"批量发送文件"),('file_get',"批量下载文件"))
    task_type = models.CharField(choices=task_type_choices,max_length=50)
    user = models.ForeignKey('UserProfile')
    hosts = models.ManyToManyField('BindHosts')
    cmd = models.TextField()
    expire_time = models.IntegerField(default=30)
    task_pid = models.IntegerField(default=0)
    note = models.CharField(max_length=100,blank=True,null=True)
    def __unicode__(self):
        return "taskid:%s cmd:%s" %(self.id,self.cmd)
    class Meta:
        verbose_name = u'批量任务'
        verbose_name_plural = u'批量任务'

class TaskLogDetail(models.Model):
    child_of_task = models.ForeignKey('TaskLog')
    bind_host  = models.ForeignKey('BindHosts')
    date = models.DateTimeField(auto_now_add=True) #finished date
    event_log = models.TextField()
    result_choices= (('success','Success'),('failed','Failed'),('unknown','Unknown'))
    result = models.CharField(choices=result_choices,max_length=30,default='unknown')
    note = models.CharField(max_length=100,blank=True)

    def __unicode__(self):
        return "child of:%s result:%s" %(self.child_of_task.id, self.result)
    class Meta:
        verbose_name = u'批量任务日志'
        verbose_name_plural = u'批量任务日志'

class Token(models.Model):
    user = models.ForeignKey(UserProfile)
    host = models.ForeignKey(BindHosts)
    token = models.CharField(max_length=64)
    date = models.DateTimeField(default=django.utils.timezone.now)
    expire = models.IntegerField(default=300)

    def __unicode__(self):
        return '%s : %s' %(self.host.host.ip_addr,self.token)



#test
class Test(models.Model):
    test = models.CharField(max_length=32)
    num = models.IntegerField()

    def __unicode__(self):
        return self.test

CrazyEye-master/CrazyEye-master/templates/crontab.html
{% extends 'index.html' %}

{% block page-content %}

    <div class="panel">

        <div class="panel-body">
            <h2>开发者:小主莫急,此页正在施工中！</h2>
            <h2>用户:那放上来干屁？</h2>
            <h2>开发者:我愿意我愿意我愿意,用你管！</h2>
            <h2>用户:。。。。擦，有本事告诉我你是谁，我保证不打死你！</h2>
            <h2>开发者:加群Python自动化交流群255012808</h2>
            <h2>开发者:加群Python开发之路 304154367</h2>
        </div>

    </div>

{% endblock %}

CrazyEye-master/CrazyEye-master/templates/host_detail.html
{% extends 'index.html' %}
{% load custom_tag %}

{% block page-title %}
主机详情
{% endblock %}
{% block page-content %}

<div class="row">
     <div class="col-sm-6 col-lg-3">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">主机列表</h3>
            </div>
            <div  class="panel-body " >

                      <input type="text" oninput="SearchHost(this)" id="host_search" class="form-control" placeholder="查找主机...">



                <div id="host_list">
                    <div style="margin-bottom:0;" class="list-group bg-trans">
                     {% for host in all_hosts %}

                            {% if host.id == current_host_id %}
                                <a class="list-group-item active" host_id="{{ host.id }}" href="/host/detail/?host_id={{host.id }}">{{ host.hostname }}({{ host.ip_addr }})</a>
                            {% else %}
                                <a class="list-group-item" host_id="{{ host.id }}" href="/host/detail/?host_id={{host.id }}" >{{ host.hostname }}({{ host.ip_addr }})</a>
                            {% endif %}
                     {% endfor %}
                     </div>
                </div>




            </div>
        </div>
     </div>

    <div class="col-sm-6 col-lg-9">
        <div class="panel">
             <div class="panel-heading">
                <h3 class="panel-title">主机信息</h3>
            </div>
            <div class="panel-body" >

                {% for host in all_hosts %}

                    {% if host.id == current_host_id %}
                    <div class="row" >
                        <label class="col-md-2 control-label">主机名(IP)</label>
                        <div  class="col-md-9 ">
                            <b>{{ host }}</b>
                        </div>
                    </div>
                    <div class="row" >
                        <label class="col-md-2 control-label">操作系统</label>
                        <div  class="col-md-9 ">
                            <b>{{ host.system_type }}</b>
                        </div>
                    </div>
                    <div class="row" >
                        <label class="col-md-2 control-label">端口</label>
                        <div  class="col-md-9 ">
                            <b>{{ host.port }}</b>
                        </div>
                    </div>

                    <div class="row" >
                        <label class="col-md-2 control-label">所在机房</label>
                        <div  class="col-md-9 ">
                            <b>{{ host.idc }}</b>
                        </div>
                    </div>
                    <div class="row" >
                        <label class="col-md-2 control-label">主机状态</label>
                        <div  class="col-md-9 ">
                            {% if host.enabled %}
                            <span class="badge badge-success">已启用</span>
                            {% else %}
                            <span class="badge badge-danger">已停用</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row" >
                        <label class="col-md-2 control-label">所在机房</label>
                        <div  class="col-md-9 ">
                            <b>{{ host.idc }}</b>
                            <hr/>
                        </div>

                    </div>

                    <div class="row" >
                        <label class="col-md-2 control-label">已绑定远程用户信息</label>
                        <div  class="col-md-9 ">
                            {% for bind_host in host.bindhosts_set.select_related %}
                            <div><b>{{ bind_host.host_user.username }}
                                -->属组:{% for group in  bind_host.host_group.select_related %}
                                    <span class="badge badge-info">{{ group.name }}</span>{% endfor %}</b>
                                {% if not bind_host.enabled %}<span class="badge badge-danger">此账户已禁用</span>{% endif %}
                            </div>

                            {% endfor %}
                        </div>
                    </div>


                    <div class="row" >
                        <hr/>
                        <label class="col-md-2 control-label panel-title">用户访问纪录</label>

                        <table class="table table-hover">
                            <tr>
                                <th>#</th>
                                <th>操作用户</th>
                                <th>远程用户</th>
                                <th>登录日期</th>
                                <th>登出日期</th>
                                <th>命令数</th>
                                <th>状态</th>

                            </tr>
                            {% for log in access_records %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td data-label="hostname" class="hide" >{{ log.host.host.hostname }}</td>
                                <td>{{ log.user.name }}</td>
                                <td data-label="username">{{ log.host.host_user.username }}</td>
                                <td data-label="login-date">{{ log.date |date:"Y-m-d H:i:s" }}</td>
                                <td data-label="logout-date">{% query_logout_date  log.session.auditlog_set.select_related 'action_type' 2 %}</td>
                                <td ><a href="#" onclick="ShowRecordDetail(this,'{{ log.session.id }}')" class="btn-link">{{ log.session.auditlog_set.select_related.count }}</a></td>
                                {% if log.session.closed %}
                                    <td ><span class="badge badge-info">已结束</span></td>
                                {% else %}
                                    <td><span class="badge badge-warning">连接中</span></td>
                                {% endif %}
                            </tr>
                            {% endfor %}

                        </table>
                        <div class="pagination pull-right ">
                            {% pagenator2 access_records 'host_id' current_host_id %}
                        </div>
                    </div>




                    {% endif %}

                {% endfor %}

            </div>
        </div>
    </div>

</div>
{% endblock %}

{% block bottom-js %}
<script type="text/javascript">

    $(document).ready(function(){

        host_list = {};
        $("#host_list div").children().each(function(index){

          host_list[$(this).attr("host_id")] = $(this).text();
        });

        $("#host_list a[host_id='" + "{{ current_host_id }}" + "']").prependTo("#host_list div");
        console.log($("#host_list active")[0])


    });//end doc ready

    function SearchHost(ele){

        var search_str = $(ele).val()
        var host_list_html ='' ;

        $.each(host_list,function(host_id,val){
            if (val.indexOf(search_str) >-1){
                console.log(val);
                var html_row = "<a class='list-group-item' host_id='" + host_id + "' href='/host/detail/?host_id=" + host_id + "' > " + val + "</a>";
                host_list_html += html_row ;

            }

        });//end each

        $("#host_list").html(host_list_html);
    }


</script>
{% endblock %}

CrazyEye-master/CrazyEye-master/templates/host_list_menu_component.html
        <div class="col-sm-7 col-lg-3 host_list_div" >
             <div class="panel" style="padding:0 20px 80px 20px" >
                <div class="pannel-heading">
                    <h3 class="panel-title">主机组 <span class="label label-info">已选: <b id="total_chosen_hosts">0</b>台</span></h3>
                    <span id="unfold-all" class="label label-success">展开</span>
                    <span id="collapse-all" class="label label-success">收缩</span>
                    <span id="show-all-checked" class="label label-success">已选</span>
                    <span id="show-all-unchecked" class="label label-success">未选</span>
                    <span id="check-all" class="label label-success">全选</span>
                    <span id="uncheck-all" class="label label-success">取消全选</span>


                </div>
                <div class="pannel-body">
                    <div class="searchbox">
                            <div class="input-group custom-search-form">
                                <input type="text" id="search-host" class="form-control" placeholder="搜索主机..">
                                <span class="input-group-btn">
                                    <button class="text-muted" type="button"><i class="fa fa-search"></i></button>
                                </span>
                            </div>
                    </div>
                    {#% for g_id,data in host_groups.items %#}
                    <!--未分类主机-->
                        <div class="" style="padding-top:5px;pdding-bottom:0px;">

                            <!--Block level checkboxes-->
                            <!--===================================================-->
                            <form  class="form-block host-list">
                                <ul class="list-group">
                                    <li style="border:0px;padding:0px" class="list-group-item">
                                        <span class="badge badge-primary"><i class="fa fa-chevron-down " id="group_toggle_-2" onclick="ToggleGroup(-2)"></i></span>
                                        <span data_label="group" class="badge badge-primary">全选</span>
                                        <b>未分类主机 [{{  request.user.userprofile.bind_hosts.select_related.count }}]</b>
                                    </li>

								</ul>

                                {% for host in  request.user.userprofile.bind_hosts.select_related %}
                                    <label input_label='host' style='display:none'  class="form-checkbox form-normal form-primary form-text active">
                                        <input type="checkbox" id="host_{{ host.id }}" >{{ host.host.hostname }}({{ host.host.ip_addr }}) @ {{ host.host_user.username }}
                                    </label>
                                {% endfor %}


                            </form>
                            <!--===================================================-->

                        </div>
                        <hr style="margin:0px">

                    <!--end未分类主机-->

                    {% for g in request.user.userprofile.host_groups.select_related  %}
                        <div class="" style="padding-top:5px;pdding-bottom:0px;">

                            <!--Block level checkboxes-->
                            <!--===================================================-->
                            <form  class="form-block host-list">
                                <ul class="list-group">
                                    <li style="border:0px;padding:0px" class="list-group-item">
                                        <span class="badge badge-primary"><i class="fa fa-chevron-down " id="group_toggle_{{ g.id }}" onclick="ToggleGroup({{ g.id }})"></i></span>
                                        <span data_label="group" class="badge badge-primary">全选</span>
                                        <b>{{ g.name }} [{{  g.bindhosts_set.select_related.count}}]</b>
                                    </li>

								</ul>

                                {% for host in  g.bindhosts_set.select_related %}
                                    <label input_label='host' style='display:none'  class="form-checkbox form-normal form-primary form-text active">
                                        <input type="checkbox" id="host_{{ host.id }}" >{{ host.host.hostname }}({{ host.host.ip_addr }}) @ {{ host.host_user.username }}
                                    </label>
                                {% endfor %}


                            </form>
                            <!--===================================================-->

                        </div>
                        <hr style="margin:0px">

                    {% endfor %}

                </div>

             </div>
        </div>

CrazyEye-master/CrazyEye-master/templates/user_audit.html
{% extends 'index.html' %}
{% load custom_tag %}

{% block page-title %}
用户审计
{% endblock %}
{% block page-content %}
<div class="row" >
    <div class="col-sm-6 col-lg-3">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">用户列表</h3>
            </div>
            <div class="panel-body" >
                <div class="list-group bord-no">

                {% for department in department_list %}
                    <a data-label="department-name" class=" list-group-item" href="#"><b>{{ department }}</b><span style="color:red" class="badge badge-info">{{ department.userprofile_set.select_related|length }}</span></a>
                    {% for user in department.userprofile_set.select_related %}

                        <a data-label="username"  user-id="{{ user.id }}" style="margin-left:2%;width:96%" class="list-group-item  collapse" href="/user_audit/{{ user.id }}/">&nbsp;&nbsp;&nbsp;{{ user.name }}</a>
                    {% endfor %}
                {% endfor %}
                </div>
            </div>
        </div>

    </div> <!--end col-lg-3-->
    <div class="col-sm-6 col-lg-9">
        <div class="panel">

            <div class="panel-body" style="margin-left:0" >

                <div class="row" >
                    <label class="col-md-2 control-label">账户</label>
                    <div  class="col-md-9 ">
                        <b>{{ user_obj.name}}</b>

                    </div>
                </div>
                <div class="row" >
                    <label class="col-md-2 control-label">部门</label>
                    <div  class="col-md-9 ">
                        <b>{{ user_obj.department.name}}</b>

                    </div>
                </div>
                <div class="row" >
                    <label class="col-md-2 control-label">账户有效期</label>
                    <div  class="col-md-9 ">
                        从 <b>{{ user_obj.valid_begin_time }}</b> 至 <b>{{ user_obj.valid_end_time }}</b>
                        <hr/>
                    </div>
                </div>
                <div class="row" >
                    <label class="col-md-2 control-label">可管理主机组</label>
                    <div  class="col-md-9 ">
                        {% for group in user_obj.host_groups.select_related %}
                        {{ group.name }}<br>
                        {% endfor %}
                    <hr/>
                    </div>
                </div>

                <div class="row" >
                    <label class="col-md-2 control-label">可操作主机列表</label>
                    <div  class="col-md-9 ">

                        <table class="table  table-hover table-condensed">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>主机名</th>
                                <th>IP</th>
                                <th>远程用户</th>
                            </tr>
                        </thead>
                        <tbody>
                         {% for bind_host in user_obj.bind_hosts.select_related %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="#fakelink" class="btn-link">{{ bind_host.host.hostname}}</a></td>
                                <td>{{  bind_host.host.hostname }} </td>
                                <td>{{  bind_host.host_user.username }} </td>
                            </tr>

                        {% endfor %}

                        </tbody>
                        </table>


                     <hr/>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="row">
    <div class="col-sm-6 col-lg-12">

        <div class="panel panel-primary">

            <!--Panel heading-->
            <div class="panel-heading">
                <div class="panel-control">

                    <!--Nav tabs-->
                    <ul class="nav nav-tabs">
                        {% if data_type == 'multi_task' %}

                            <li class=""><a data-toggle="tab" href="#demo-tabs-box-1" aria-expanded="true">单机操作</a>
                            </li>
                            <li class="active"><a data-toggle="tab" href="#demo-tabs-box-2" aria-expanded="false">批量操作</a>
                            </li>
                        {% else %}
                            <li class="active"><a data-toggle="tab" href="#demo-tabs-box-1" aria-expanded="true">单机操作</a>
                            </li>
                            <li class=""><a data-toggle="tab" href="#demo-tabs-box-2" aria-expanded="false">批量操作</a>
                            </li>
                        {% endif %}
                    </ul>

                </div>
                <h3 class="panel-title"><b>{{ user_obj.name }}</b> 的操作纪录</h3>
            </div>

            <!--Panel body-->
            <div class="panel-body">

                <!--Tabs content-->
                <div class="tab-content">
                    {% if data_type == 'multi_task' %}
                    <div id="demo-tabs-box-1" class="tab-pane fade">
                    {% else %}
                    <div id="demo-tabs-box-1" class="tab-pane fade active in ">
                    {% endif %}
                      <table class="table  table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th>#</th>

                                    <th>主机名</th>
                                    <th>IP</th>
                                    <th>远程用户</th>
                                    <th>登录日期</th>
                                    <th>登出日期</th>
                                    <th>操作指令数</th>
                                    <th>#</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for record in user_login_records %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td data-label="hostname"><a href="#fakelink" class="btn-link">{{ record.host.host.hostname}}</a></td>
                                    <td data-label="ip_addr">{{ record.host.host.ip_addr }} </td>
                                    <td data-label="username">{{ record.host.host_user.username }} </td>
                                    <td data-label="login_date"><b >{{ record.date|date:"Y-m-d H:i" }}</b> </td>
                                    <td data-label="logout_date">{{ record.session.auditlog_set.select_related.last.date|date:"Y-m-d H:i" }} </td>
                                    <td>{{ record.session.auditlog_set.select_related.count}} </td>
                                    <td><a onclick="ShowRecordDetail(this,'{{ record.session.id }}')"  class="badge badge-success">查看详细</a> </td>
                                </tr>
                                {% endfor %}
                           </tbody>

                      </table>

                    <div class="pagination pull-right ">
                        {% pagenator user_login_records 'cmd_log' %}
                    </div>

                    </div>
                    {% if data_type == 'multi_task' %}
                    <div id="demo-tabs-box-2" class="tab-pane fade active in">
                    {% else %}
                    <div id="demo-tabs-box-2" class="tab-pane fade">
                    {% endif %}

                          <table class="table  table-hover table-condensed">
                                <thead>
                                    <tr>
                                        <th>#</th>

                                        <th>任务ID</th>
                                        <th>任务类型</th>
                                        <th>任务内容</th>
                                        <th>成功数</th>
                                        <th>失败数</th>
                                        <th>未知数</th>
                                        <th>详细</th>


                                    </tr>
                                </thead>
                                <tbody>
                                    {% for record in multitask_records %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ record.id }}</td>
                                        <td>{{ record.task_type }}</td>
                                        <td>{{ record.cmd }}</td>
                                         <td>{% query_set record.tasklogdetail_set "result" "success" %}</td>
                                        <td>{% query_set record.tasklogdetail_set "result" "failed" %}</td>
                                        <td>{% query_set record.tasklogdetail_set "result" "unknown" %}</td>
                                        <td><a class="badge badge-info" href="{% url 'multi_task_log_detail' record.id %}">查看详细</a></td>

                                    </tr>
                                    {% endfor %}
                               </tbody>

                          </table>

                        <div class="pagination pull-right ">
                            {% pagenator multitask_records 'multi_task' %}
                        </div>


                    </div>
                </div>
            </div>
        </div>



    </div> <!--end col-sm-6 col-lg-12-->
</div>

{% include 'user_audit_modal.html' %}


{% endblock %}
{% block aside-bar %}

{% endblock %}
{% block bottom-js %}
{% include 'user_audit_js.html' %}
<script type="text/javascript" >


    $(document).ready(function(){

        if ("{{ data_type }}" == 'multi_task'){

        }

        $("a[data-label='department-name']").click(function(){
            $(this).toggleClass('active');

            $(this).nextUntil("a[data-label='department-name']").toggleClass("collapse");
        });//end click
        $("a[data-label='username']").click(function(){

            $(this).parent().children("a[data-label='username']").removeClass("btn-default");
            $(this).addClass("btn-default");

        });//end click


        //highlight the active user when page loaded
        var active_user_ele = $("a[user-id='{{ user_obj.id }}']");
        active_user_ele.toggleClass("collapse");
        if (active_user_ele.prev().attr('data-label') == 'department-name'){
            active_user_ele.prev().toggleClass('active');
        }else{
            var parent_node = active_user_ele.prevUntil("a[data-label='department-name']")[0];
            $(parent_node).prev().toggleClass('active');

        }
        //end highlight the active user when page loaded

    });


</script>
{% endblock %}