hostMS/host/urls.py
from django.conf.urls import include, url
from  host import views

urlpatterns = [
    url(r'^host_mgr/$', views.host_mgr,name='host_mgr'),
]

hostMS/hostMS/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from host.views import *
# from django.core.management import execute_from_command_line
from host import urls as host_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', index,name='dashboard'),
    url(r'^',include(host_urls)),
    url(r'^$', hosts, name='hosts'),
    url(r'^assets/$', assets, name='assets'),
    url(r'^monitor/$', monitor, name='monitor'),
    url(r'^acc_login/$', acc_login, name='acc_login'),
]

hostMS/host/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from auth_models import UserProfile
# Create your models here.

class Host(models.Model):
    hostname = models.CharField(max_length=64)
    ip_addr = models.GenericIPAddressField(unique=True)
    system_type_choices= (
        ('linux','Linux'),
        ('windows','Windows')
    )
    system_type = models.CharField(choices=system_type_choices,max_length=32,default='linux')
    port = models.SmallIntegerField(default=22)
    idc = models.ForeignKey('IDC')
    enabled = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return '%s(%s)' % (self.hostname,self.ip_addr)

class IDC(models.Model):
    name = models.CharField(max_length=32,unique=True)
    memo = models.TextField(blank=True,null=True)

    def __unicode__(self):
        return self.name

class HostUser(models.Model):
    auth_type_choices = (
        ('ssh-password','SSH/Password'),
        ('ssh-key','SSH/KEY')
    )
    auth_type = models.CharField(choices=auth_type_choices, max_length=32,default='ssh-password')
    username = models.CharField(max_length=64)
    password = models.CharField(max_length=254,blank=True,null=True)

    def __unicode__(self):
        return '(%s)%s ' %(self.auth_type,self.username)


class BindHostToUser(models.Model):
    host = models.ForeignKey(Host)
    host_user = models.ForeignKey(HostUser)
    host_groups  = models.ManyToManyField('HostGroup')

    def get_groups(self):
        return ','.join([g.name for g in self.host_groups.select_related()])

    def __unicode__(self):
        return '%s:%s' %(self.host,self.host_user)

    class Meta:
        unique_together=('host','host_user')

class HostGroup(models.Model):
    name = models.CharField(max_length=64,unique=True)

    def __unicode__(self):
        return self.name






# class IDC(models.Model):
#     name = models.CharField(max_length=20,unique=True)
#
# class Host(models.Model):
#     name = models.CharField(max_length=20)
#     ip = models.GenericIPAddressField()
#     port = models.IntegerField(default=22)
#     system_choices = (('LINUX','linux'),('WINDOWS','windows'),)
#     system = models.CharField(max_length=10,choices=system_choices,default='linux')
#     idc = models.ForeignKey(IDC)
#
# class HostGroup(models.Model):
#     name = models.CharField(max_length=20,unique=True)
#
# class HostUser(models.Model):
#     uname = models.CharField(max_length=30)
#     pwd = models.CharField(max_length=60)
#
# class Department(models.Model):
#     name = models.CharField(max_length=20,unique=True)
#
# class UserProfile(models.Model):
#     user = models.OneToOneField(User)
#     uname = models.CharField(max_length=20)
#     pwd = models.CharField(max_length=60)
#     dept = models.ManyToManyField(Department)
#     host_group = models.ManyToManyField(HostGroup)
#
# class BindHostToUser(models.Model):
#     host = models.ForeignKey(Host)
#     host_user = models.ForeignKey(HostUser)
#     host_group = models.ManyToManyField(HostGroup)

hostMS/host/views.py
#coding:utf8
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from models import *
# Create your views here.

def index(req):
    return render(req,'index.html')

def hosts(req):
    return render(req,'hosts.html')

def assets(req):
    return render(req,'assets.html')

def monitor(req):
    return render(req,'monitor.html')

def acc_login(request):
    if request.method == 'GET':
        return render(request,'login.html')
    else:
        print request.POST
        username = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            return HttpResponseRedirect('/')
        else:
            return render(request,'login.html',{'log_err':"Wrong username or password!"})

def host_mgr(request):
    select_group_id = request.GET.get("selected_group")
    if select_group_id:
        host_list = BindHostToUser.objects.filter(host_groups=select_group_id)
        # host_list = BindHostToUser.objects.filter(host_groups__id=select_group_id) # 关联查询
    else:
        host_list = request.user.bind_hosts.select_related()
    return render(request,'hosts/host_mgr.html',{'active_main_node':'/hosts/','host_list':host_list})

hostMS/templates/assets.html
{% extends 'base.html' %}

{% block sidebar %}

    index

{% endblock %}


{% block content-panel %}

    Assets

{% endblock %}

hostMS/templates/base.html
<!DOCTYPE html>
<!-- saved from url=(0043)http://getbootstrap.com/examples/dashboard/ -->
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>WildHunt</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/dashboard.css" rel="stylesheet">

</head>

<body>
{% csrf_token %}
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">WildHunt</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul id="top-navbar" class="nav navbar-nav ">
{#                <li><a href="{% url 'dashboard' %}">Dashboard</a></li>#}
                <li><a href="{% url 'hosts' %}">主机管理</a></li>
                <li><a href="{% url 'assets' %}">资产</a></li>
                <li><a href="{% url 'monitor' %}">监控</a></li>
            </ul>

            <ul id="top-navbar" class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ request.user.email }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div id="sidebar-menu" class="col-sm-3 col-md-2 sidebar">
            {% block sidebar %}
                <ul class="nav nav-sidebar">
                    <li class="active"><a href="http://getbootstrap.com/examples/dashboard/#">Overview <span
                            class="sr-only">(current)</span></a></li>
                    <li><a href="#">Reports</a></li>
                    <li><a href="#">Analytics</a></li>
                    <li><a href="#">Export</a></li>
                </ul>
            {% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block content-panel %}
                <h1 class="page-header">Dashboard</h1>

                <div class="row placeholders">
                    <div class="col-xs-6 col-sm-3 placeholder">
                        <img data-src="holder.js/200x200/auto/sky" class="img-responsive"
                             alt="Generic placeholder thumbnail">
                        <h4>Label</h4>
                        <span class="text-muted">Something else</span>
                    </div>
                    <div class="col-xs-6 col-sm-3 placeholder">
                        <img data-src="holder.js/200x200/auto/vine" class="img-responsive"
                             alt="Generic placeholder thumbnail">
                        <h4>Label</h4>
                        <span class="text-muted">Something else</span>
                    </div>
                    <div class="col-xs-6 col-sm-3 placeholder">
                        <img data-src="holder.js/200x200/auto/sky" class="img-responsive"
                             alt="Generic placeholder thumbnail">
                        <h4>Label</h4>
                        <span class="text-muted">Something else</span>
                    </div>
                    <div class="col-xs-6 col-sm-3 placeholder">
                        <img data-src="holder.js/200x200/auto/vine" class="img-responsive"
                             alt="Generic placeholder thumbnail">
                        <h4>Label</h4>
                        <span class="text-muted">Something else</span>
                    </div>
                </div>
            {% endblock content-panel %}
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/js/jquery-2.1.1.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        if ("{{ active_main_node }}" == '') {

            $("#top-navbar a[href='{{ request.path }}']").parent().addClass("active");

        } else {
            $("#top-navbar a[href='{{ active_main_node }}']").parent().addClass("active");
            $("#sidebar-menu a[href='{{ request.path  }}']").parent().addClass("active");
        }
    });
</script>
{% block bottom-js %}
{% endblock %}
</body>
</html>

hostMS/templates/hosts.html
{% extends 'base.html' %}

{% block sidebar %}

    <ul class="nav nav-sidebar">
        <li>
            <a href="{% url 'host_mgr' %}">主机</a>
        </li>
{#        <li>#}
{#            <a href="{% url 'multi_cmd' %}">批量命令</a>#}
{#        </li>#}
{#        <li>#}
{#            <a href="{% url 'multi_file_transfer' %}">文件分发</a>#}
{#        </li>#}
{#        <li>#}
{#            <a href="{% url 'task_cron' %}">任务编排</a>#}
{#        </li>#}

    </ul>

{% endblock %}


{% block content-panel %}

    HOST

{% endblock %}

hostMS/templates/hosts/host_mgr.html
{% extends 'hosts.html' %}


{% block content-panel %}

    <h3>可管理主机列表</h3>

    <div>
        <div class="col-lg-3">
            <div  style="margin-left:-35px" class="panel panel-info">
              <div class="panel-title">
                  主机组
              </div>
              <div class="panel-body">

                <div class="list-group">
                  <a href="{% url 'host_mgr' %}" class="list-group-item active">
                    未分组主机 [{{ request.user.bind_hosts.count }}]
                  </a>
                  {% for group in request.user.host_groups.all %}
                      <a href="{% url 'host_mgr' %}?selected_group={{ group.id }}" class="list-group-item ">
                        {{ group.name }} [{{ group.bindhosttouser_set.count }}]
                      </a>
                  {% endfor %}
                </div>
              </div>
            </div> <!--end panel-->
        </div>
        <div class="col-lg-9">

            <div style="margin-left:-15px" class="panel panel-info">
              <div class="panel-title">
                  主机列表
              </div>
              <div class="panel-body">
                 <table class="table table-hover">
                    <tr>
                        <th>#</th>
                        <th>Hostname</th>
                        <th>IP</th>
                        <th>Port</th>
                        <th>System type</th>
                        <th>IDC</th>
                        <th>Status</th>
                        <th>Login</th>

                    </tr>
                   {% for host in host_list %}

                       <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ host.host.hostname }}</td>
                        <td>{{ host.host.ip_addr }}</td>
                        <td>{{ host.host.port }}</td>
                        <td>{{ host.host.system_type }}</td>
                        <td>{{ host.host.idc }}</td>
                        <td>{{ host.host.enabled }}</td>
                        <td>Login</td>

                       </tr>
                    {% endfor %}

                  </table>

              </div>
            </div> <!--end panel-->

        </div>
    </div>

{% endblock %}

hostMS/templates/hosts/multi_cmd.html
{% extends 'hosts.html' %}


{% block content-panel %}

    <h3>批量命令</h3>

    <div>
        <div class="col-lg-3">
            <div  style="margin-left:-35px" class="panel panel-info">
              <div class="panel-title">
                  主机组
              </div>
              <div class="panel-body">

                <div id="host-group" class="list-group">
                  <a href="#" gid="-1" class="list-group-item active">
                    未分组主机 [{{ request.user.bind_hosts.select_related.count }}]
                  </a>
                  {% for group in request.user.host_groups.select_related %}
                      <a gid="{{ group.id }}" href="#" onclick="GetHostList({{ group.id }},this)" class="list-group-item ">
                        {{ group.name }} [{{ group.bindhosttouser_set.select_related.count }}]
                      </a>
                  {% endfor %}
                </div>


              </div>
            </div> <!--end panel-->
        </div>
        <div class="col-lg-9">

            <div style="margin-left:-15px" class="panel panel-info">
              <div class="panel-title">
                  任务信息
              </div>
              <div class="panel-body">
                <div class="host-list">
                    <ol>
                    </ol>

                </div>
                <hr />

                <div class="execution-box">
                    <form method="post" action="{% url 'multi_cmd_exec' %}">
                      <div class="form-group">
                        <label for="exampleInputEmail1">命令</label>
                        <textarea type="text" class="form-control" name="cmd" id="cmd" placeholder="输入要执行的命令..." > </textarea>
                      </div>

                      <div class="checkbox">
                        <!--label>
                          <input type="checkbox"> Check me out
                        </label-->
                      </div>
                    </form>
                    <button type="button" onclick="post_task('cmd')" class="btn btn-success">提交执行</button>

                </div>

              </div>
            </div> <!--end panel-->

             <div class="row">

             <div class="panel panel-info">
                  <div class="panel-title">
                      任务执行结果
                  </div>
                  <div id="task_result" class="panel-body">
                      dff
                  </div>

              </div>
             </div>



        </div>
    </div>

{% endblock %}

{% block bottom-js %}
<script type="text/javascript">
    $(document).ready(function(){




    });//end doc
    function post_task(task_type){
        var active_group_id = $("#host-group a").filter(".active").attr("gid");
        //console.log(active_group);
        if (task_type == 'cmd'){
            cmd_val = $("#cmd").val();

            MultiCmdExec(cmd_val,active_group_id,task_type);
        }

    }

    function  MultiCmdExec(cmd_val,active_group_id,task_type){

        $.post("{% url 'multi_cmd_exec' %}", {
            'cmd':cmd_val,
            'gid':active_group_id,
            'task_type':task_type,
            'csrfmiddlewaretoken': $("input[name='csrfmiddlewaretoken']").val()
        },function(callback){
            console.log(callback);
            callback = JSON.parse(callback);
            GetTaskResult(callback);


        });//end post
    }

    function GetTaskResult(callback){
        task_id = callback.task_id;
        console.log(task_id);
        setInterval(function(){

             $.getJSON("{% url 'get_task_res' %}", {'task_id': task_id},function(res){
                console.log(res);
                DiskTaskResult(res);
            });//end getJson

        },3000 );

    }

    function DiskTaskResult(res){
         $("#task_result").html(' ');
        $.each(res.task_result,function(index,cmd_result){
            console.log(cmd_result);
            var res_html = "<div class=row>" +
                            "<p>" + cmd_result.bind_host__host__hostname + "(" + cmd_result.bind_host__host__ip_addr  + ")" + "-->" + cmd_result.bind_host__host_user__username + "</p>" +
                            "<pre>" + cmd_result.event_log + "</pre>" +
                            "</div>";


            $("#task_result").append(res_html);

        });//end each

    }


    function GetHostList(gid,self){
        $(self).addClass("active");
        $(self).siblings().removeClass("active");

        $(".host-list ol").html(" ");
        $.getJSON("{% url 'get_host_list' %}", {'gid':gid},function(callback){

            console.log(callback);

            $.each(callback,function(index,val){
               console.log(index + '--' + val);
               var li_html = "<li>" + val.host__hostname + "(" + val.host__ip_addr + ")" + " --> " + val.host_user__username + "</li>";
               $(".host-list ol").append(li_html);
            });

        });//end getJson

    }

</script>


{% endblock %}

hostMS/templates/hosts/multi_file_transfer.html
{% extends 'hosts.html' %}



{% block content-panel %}

    file transfer

{% endblock %}

hostMS/templates/hosts/task_cron.html
{% extends 'hosts.html' %}


{% block content-panel %}

task cron
{% endblock %}

hostMS/templates/index.html
{% extends 'base.html' %}

{% block sidebar %}

    <ul class="nav nav-sidebar">
        <li>
            <a href="{% url 'host_mgr' %}">主机</a>
        </li>
        <li>
            <a href="/">批量命令</a>
        </li>
        <li>
            <a href="/">文件分发</a>
        </li>
        <li>
            <a href="/">任务编排</a>
        </li>
    </ul>

{% endblock %}


{% block content-panel %}

    INDEX

{% endblock %}

hostMS/templates/login.html
<!DOCTYPE html>
<!-- saved from url=(0038)http://v3.bootcss.com/examples/signin/ -->
<html lang="zh-CN"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">

    <title>KingSlayer</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/signin.css" rel="stylesheet">

  </head>

  <body>

    <div class="container">

      <form class="form-signin" action="{% url 'acc_login' %}" method="post">{% csrf_token %}
        <h3 class="form-signin-heading">KingSlayer登录</h3>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required="">
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p style="color:red;">{{ log_err }}</p>
      </form>

    </div> <!-- /container -->



</body></html>

hostMS/templates/monitor.html
{% extends 'base.html' %}

{% block sidebar %}

    index

{% endblock %}


{% block content-panel %}

    Monitor

{% endblock %}